// Camille Saint-Saëns, Joshua Bell, The Carnival of the Animals, R. 125 XIII. The Swan (Joel)

const playlist = [
  {
    videoId: '7A7v-wK8j7g',
    name: 'Concerto Grosso, Op. 6, No. 8 in G Minor ("Christmas Concerto")',
    date: 1714,
    aka: 'Christmas Concerto',
    key: 'G Minor',
    number: 8,
    opus: 6,
    collection: 'Twelve concerti grossi',
    url: 'https://en.wikipedia.org/wiki/Christmas_Concerto_(Corelli)',
    by: 'Arcangelo Corelli',
    byUrl: 'https://en.wikipedia.org/wiki/Arcangelo_Corelli',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Arcangelo_Corelli_2.jpg/340px-Arcangelo_Corelli_2.jpg',
    performedBy: 'Philharmonia Baroque Orchestra',
    contributedBy: 'Tim Pratt',
  },
  {
    videoId: 'mGQLXRTl3Z0',
    startDate: 1717,
    date: 1723,
    name: 'Cello Suite No. 1',
    bwv: 1007,
    number: 1,
    key: 'G Major',
    collection: 'Cello Suites',
    url: 'https://en.wikipedia.org/wiki/Cello_Suites_(Bach)#Suite_No._1_in_G_major,_BWV_1007',
    by: 'Johann Sebastian Bach',
    byUrl: 'https://en.wikipedia.org/wiki/Johann_Sebastian_Bach',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/93/Young_Bach2.jpg',
    contributedBy: 'Robert Rowat (https://www.cbcmusic.ca/posts/11372/10-pieces-of-classical-music-everyone-should-know)',
  },
  {
    videoId: 'b4IXXpTHjok',
    startDate: 1764,
    date: 1771,
    name: 'Symphony No. 1',
    number: 1,
    url: 'https://en.wikipedia.org/wiki/Symphony_No._1_(Mozart)',
    by: 'Wolfgang Amadeus Mozart',
    byUrl: 'https://en.wikipedia.org/wiki/Wolfgang_Amadeus_Mozart',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Wolfgang-amadeus-mozart_2.jpg/500px-Wolfgang-amadeus-mozart_2.jpg',
  },
  {
    videoId: 'YuBeBjqKSGQ',
    name: 'Der Hölle Rache (kocht in meinem Herzen)',
    translation: 'Hell\'s Vengeance (Boils in My Heart)',
    date: 1791,
    aka: 'Queen of the Night\'s Aria',
    url: 'https://en.wikipedia.org/wiki/Der_H%C3%B6lle_Rache_kocht_in_meinem_Herzen',
    by: 'Wolfgang Amadeus Mozart',
    byUrl: 'https://en.wikipedia.org/wiki/Wolfgang_Amadeus_Mozart',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Croce-Mozart-Detail.jpg/500px-Croce-Mozart-Detail.jpg',
    for: 'The Magic Flute',
    performedBy: 'Diana Damrau, The Royal Opera',
    contributedBy: 'Michelle Brownstein',
  },
  // {
  //   videoId: 'nT7_IZPHHb0',
  //   name: 'Piano Sonata No. 14 Mvt. 1',
  //   movement: 1,
  //   contributedBy: 'Brian Russell',
  // },
  // {
  //   videoId: 'TVjFceluiPo',
  //   name: 'Piano Sonata No. 14 Mvt. 3',
  //   movement: 3,
  //   contributedBy: 'Logan Sobczak',
  // },
  {
    videoId: '4Tr0otuiQuU',
    name: 'Piano Sonata No. 14',
    date: 1801,
    key: 'C Sharp Minor',
    number: 14,
    opus: 27,
    aka: 'Moonlight Sonata',
    url: 'https://en.wikipedia.org/wiki/Piano_Sonata_No._14_(Beethoven)',
    by: 'Ludwig Von Beethoven',
    byUrl: 'https://en.wikipedia.org/wiki/Ludwig_van_Beethoven',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Beethoven_Hornemann.jpg/340px-Beethoven_Hornemann.jpg',
    contributedBy: 'Nick Forneris',
  },
  {
    videoId: '6z4KK7RWjmk',
    startDate: 1804,
    date: 1808,
    name: 'Symphony No. 5',
    number: 5,
    key: 'C Minor',
    opus: 67,
    aka: 'Beethoven\'s Fifth',
    url: 'https://en.wikipedia.org/wiki/Symphony_No._5_(Beethoven)',
    by: 'Ludwig Von Beethoven',
    byUrl: 'https://en.wikipedia.org/wiki/Ludwig_van_Beethoven',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Beethoven_3.jpg/500px-Beethoven_3.jpg',
    contributedBy: 'Robert Rowat (https://www.cbcmusic.ca/posts/11372/10-pieces-of-classical-music-everyone-should-know)',
  },
  {
    videoId: 'PvdZ1xIgv08',
    date: 1823,
    name: 'Du bist die Ruh',
    translation: 'You are Rest and Peace',
    deutsch: 776,
    number: 3,
    opus: 59,
    url: 'https://en.wikipedia.org/wiki/Du_bist_die_Ruh%27',
    by: 'Franz Schubert',
    byUrl: 'https://en.wikipedia.org/wiki/Franz_Schubert',
    contributedBy: 'Robert Rowat (https://www.cbcmusic.ca/posts/11372/10-pieces-of-classical-music-everyone-should-know)',
  },
  {
    videoId: 'LcTPAjDWXVQ',
    name: 'Ellens Gesang III',
    translation: 'Ellen\'s Third Song',
    date: 1825,
    aka: 'Ave Maria',
    deutsch: 839,
    opus: 52,
    number: 6,
    url: 'https://en.wikipedia.org/wiki/Ave_Maria_(Schubert)',
    by: 'Franz Schubert',
    byUrl: 'https://en.wikipedia.org/wiki/Franz_Schubert',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Franz_Schubert_c1827.jpg/340px-Franz_Schubert_c1827.jpg',
    performedBy: 'The String Quartet Channel',
    contributedBy: 'Brandon Mitchell',
  },
  // {
  //   videoId: 'kzLGcNwDJW8',
  //   date: '1830-1832 (Early Romantic Period)',
  //   name: 'Nocturne Op. 9, No. 1',
  //   key: 'B Flat Minor',
  //   url: 'https://en.wikipedia.org/wiki/Nocturnes,_Op._9_(Chopin)',
  //   by: 'Frédéric Chopin',
  //   byUrl: 'https://en.wikipedia.org/wiki/Fr%C3%A9d%C3%A9ric_Chopin',
  //   imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Frederic_Chopin_photo.jpeg/440px-Frederic_Chopin_photo.jpeg',
  //   contributedBy: 'Robert Rowat (https://www.cbcmusic.ca/posts/11372/10-pieces-of-classical-music-everyone-should-know)',
  // },
  {
    videoId: 'p29JUpsOSTE',
    startDate: 1830,
    date: 1832,
    name: 'Nocturne Op. 9, No. 1',
    number: 1,
    opus: 0,
    key: 'in E Flat Major',
    url: 'https://en.wikipedia.org/wiki/Nocturnes,_Op._9_(Chopin)',
    by: 'Frédéric Chopin',
    byUrl: 'https://en.wikipedia.org/wiki/Fr%C3%A9d%C3%A9ric_Chopin',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Frederic_Chopin_photo.jpeg/440px-Frederic_Chopin_photo.jpeg',
    contributedBy: 'Nate Rushing',
  },
  {
    videoId: 'bGMsfyy-FPY',
    startDate: 1838,
    date: 1844,
    name: 'Violin Concerto Op. 64 Mvt.3',
    opus: 64,
    movement: 3,
    key: 'E Minor',
    url: 'https://en.wikipedia.org/wiki/Violin_Concerto_(Mendelssohn)',
    by: 'Felix Mendelssohn',
    byUrl: 'https://en.wikipedia.org/wiki/Felix_Mendelssohn',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Mendelssohn_Bartholdy.jpg/440px-Mendelssohn_Bartholdy.jpg',
    performedBy: 'Janine Jansen & BBC Orchestra',
    contributedBy: 'Megan Hord',
  },
  {
    videoId: 'FpK1tjbeeA0',
    startDate: 1856,
    date: 1861,
    name: 'Piano Quartet No. 1, Op. 25',
    number: 1,
    opus: 25,
    url: 'https://en.wikipedia.org/wiki/Piano_Quartet_No._1_(Brahms)',
    by: 'Johannes Brahms',
    byUrl: 'https://en.wikipedia.org/wiki/Johannes_Brahms',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/11/Johannes_Brahms_1853.jpg',
    contributedBy: 'Robert Rowat (https://www.cbcmusic.ca/posts/11372/10-pieces-of-classical-music-everyone-should-know)',
  },
  {
    videoId: 'ytpqcJ1IfoA',
    name: 'Danse macabre Op.40',
    date: 1874,
    opus: 40,
    key: 'G Minor',
    url: 'https://en.wikipedia.org/wiki/Danse_macabre_(Saint-Sa%C3%ABns)',
    by: 'Camille Saint-Saëns',
    byUrl: 'https://en.wikipedia.org/wiki/Camille_Saint-Sa%C3%ABns',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Saint-saens-1875.jpg',
    time: 60,
    contributedBy: 'Megan Hord',
  },
  {
    videoId: 'KJ_HHRJf0xg',
    date: 1875,
    name: 'Habanera',
    collection: 'Carmen',
    url: 'https://en.wikipedia.org/wiki/Habanera_(aria)',
    by: 'Georges Bizet',
    byUrl: 'https://en.wikipedia.org/wiki/Georges_Bizet',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Georges_bizet.jpg/440px-Georges_bizet.jpg',
    contributedBy: 'Robert Rowat (https://www.cbcmusic.ca/posts/11372/10-pieces-of-classical-music-everyone-should-know)',
  },
  // {
  //   videoId: 'Av31vk4613M',
  //   name: 'Lent et triste',
  //   date: 1888,
  //   key: 'C major',
  //   number: 2,
  //   collection: 'Gymnopédies',
  //   url: 'https://en.wikipedia.org/wiki/Gymnop%C3%A9dies',
  //   by: 'Erik Satie',
  //   byUrl: 'https://en.wikipedia.org/wiki/Erik_Satie',
  //   imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Satie.jpg',
  //   performedBy: 'Daniel Varsano, Philippe Entremont',
  //   contributedBy: 'Mak Aleman',
  // },
  {
    videoId: '0WNCBPdetG4',
    name: 'Trois Gymnopédies',
    date: 1888,
    url: 'https://en.wikipedia.org/wiki/Gymnop%C3%A9dies',
    by: 'Erik Satie',
    byUrl: 'https://en.wikipedia.org/wiki/Erik_Satie',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Satie.jpg',
    performedBy: 'Daniel Varsano, Philippe Entremont',
    contributedBy: 'Mak Aleman',
  },
  {
    videoId: 'UnilUPXmipM',
    name: 'Requiem Op. 48',
    startDate: 1887,
    date: 1890,
    key: 'D Minor',
    opus: 48,
    url: 'https://en.wikipedia.org/wiki/Requiem_(Faur%C3%A9)',
    by: 'Gabriel Fauré',
    byUrl: 'https://en.wikipedia.org/wiki/Gabriel_Faur%C3%A9',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Painting_of_Gabriel_Faur%C3%A9.jpg/440px-Painting_of_Gabriel_Faur%C3%A9.jpg',
    performedBy: 'Atlanta Symphony Orchestra & Chorus',
    contributedBy: 'Michelle Brownstein',
  },
  {
    videoId: 'hWTe3C_RoDo',
    startDate: 1888,
    date: 1891,
    name: 'Deux Arabesques',
    url: 'https://en.wikipedia.org/wiki/Deux_arabesques',
    by: 'Claude Debussy',
    byUrl: 'https://en.wikipedia.org/wiki/Claude_Debussy',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Debussy-by-Baschet-1884.jpg/340px-Debussy-by-Baschet-1884.jpg',
    performedBy: 'Héloïse de Jenlis (harp)',
    contributedBy: 'Joel Zerr',
  },
  {
    videoId: '-kbi1EMcD3E',
    name: 'Vesti La Giubba',
    date: 1893,
    translation: 'Put on the Costume',
    url: 'https://en.wikipedia.org/wiki/Vesti_la_giubba',
    by: 'Ruggero Leoncavallo',
    byUrl: 'https://en.wikipedia.org/wiki/Ruggero_Leoncavallo',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ruggiero_leoncavallo.jpg/340px-Ruggiero_leoncavallo.jpg',
    performedBy: 'Luciano Pavarotti',
    for: 'I Pagliacci',
    contributedBy: 'Michelle Brownstein',
  },
  {
    videoId: 'IFPwm0e_K98',
    date: 1896,
    name: 'Also Sprach Zarathustra',
    translation: 'Thus Spoke Zarathustra',
    opus: 30,
    url: 'https://en.wikipedia.org/wiki/Also_sprach_Zarathustra_(Strauss)',
    by: 'Richard Strauss',
    byUrl: 'https://en.wikipedia.org/wiki/Richard_Strauss',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Strauss1894.jpg',
    contributedBy: 'Robert Rowat (https://www.cbcmusic.ca/posts/11372/10-pieces-of-classical-music-everyone-should-know)',
  },
  {
    videoId: 'jnKFIp7CahY',
    name: 'Jeux d\'eau',
    translation: 'Water Games',
    date: 1901,
    url: 'https://en.wikipedia.org/wiki/Jeux_d%27eau_(Ravel)',
    by: 'Maurice Ravel',
    byUrl: 'https://en.wikipedia.org/wiki/Maurice_Ravel',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Maurice_Ravel_1925.jpg/440px-Maurice_Ravel_1925.jpg',
    performedBy: 'Jean-Yves Thibaudet',
    contributedBy: 'Logan Sobczak',
  },
  {
    videoId: 'rEGOihjqO9w',
    startDate: 1900,
    date: 1901,
    name: 'Piano Concerto No. 2 in C minor, Op. 18',
    number: 2,
    opus: 18,
    key: 'C minor',
    url: 'https://en.wikipedia.org/wiki/Piano_Concerto_No._2_(Rachmaninoff)',
    by: 'Sergei Rachmaninoff',
    byUrl: 'https://en.wikipedia.org/wiki/Sergei_Rachmaninoff',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Rachmaninoff_1900.jpg/440px-Rachmaninoff_1900.jpg',
    contributedBy: 'Robert Rowat (https://www.cbcmusic.ca/posts/11372/10-pieces-of-classical-music-everyone-should-know)',
  },
  {
    videoId: 'yjQbyyy8Puw',
    startDate: 1909,
    date: 1910,
    name: 'The Girl With the Flaxen Hair',
    url: 'https://en.wikipedia.org/wiki/La_fille_aux_cheveux_de_lin',
    by: 'Claude Debussy',
    byUrl: 'https://en.wikipedia.org/wiki/Claude_Debussy',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Claude_Debussy_atelier_Nadar.jpg/440px-Claude_Debussy_atelier_Nadar.jpg',
    performedBy: 'Brandon Ridenour (trumpet) & Rachel Kudo (piano)',
    contributedBy: 'Joel Zerr',
  },
  {
    videoId: '3VDUGu8NBmA',
    name: 'Images, Books 1 & 2 (Bavouzet, Thibaudet)',
    startDate: 1905,
    date: 1912,
    url: 'https://en.wikipedia.org/wiki/Images_pour_orchestre',
    by: 'Claude Debussy',
    byUrl: 'https://en.wikipedia.org/wiki/Claude_Debussy',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Claude_Debussy_ca_1908%2C_foto_av_F%C3%A9lix_Nadar.jpg/480px-Claude_Debussy_ca_1908%2C_foto_av_F%C3%A9lix_Nadar.jpg',
    contributedBy: 'Logan Sobczak',
  },
  {
    videoId: 'L0bcRCCg01I',
    name: 'Mars, the Bringer of War',
    startDate: 1914,
    date: 1916,
    opus: 32,
    movement: 1,
    collection: 'The Planets',
    url: 'https://en.wikipedia.org/wiki/The_Planets',
    by: 'Gustav Holst',
    byUrl: 'https://en.wikipedia.org/wiki/Gustav_Holst',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Gustav_Holst.jpg/440px-Gustav_Holst.jpg',
    performedBy: 'James Levine & Chicago Symphony Orchestra',
    contributedBy: 'Jon Pitts',
  },
  {
    videoId: 'GXFSK0ogeg4',
    name: 'O Fortuna',
    date: 1935,
    movement: 1,
    section: 'Fortuna Imperatrix Mundi',
    collection: 'Carmina Burana',
    url: 'https://en.wikipedia.org/wiki/O_Fortuna',
    by: 'Carl Orff',
    byUrl: 'https://en.wikipedia.org/wiki/Carl_Orff',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Carl_Orff.jpg',
    performedBy: 'Atlanta Symphony',
    contributedBy: 'Michelle Brownstein',
  },
  {
    videoId: 'CJYVH_kZkOk',
    date: 1944,
    name: 'Appalachian Spring',
    url: 'https://en.wikipedia.org/wiki/Appalachian_Spring',
    by: 'Aaron Copland',
    byUrl: 'https://en.wikipedia.org/wiki/Aaron_Copland',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Aaron_Copland_1962.JPG/440px-Aaron_Copland_1962.JPG',
    contributedBy: 'Robert Rowat (https://www.cbcmusic.ca/posts/11372/10-pieces-of-classical-music-everyone-should-know)',
  },
  {
    videoId: '1seFM7hwYKo',
    startDate: 1970,
    date: 1979,
    name: 'Glass Houses No. 5',
    number: 5,
    by: 'Ann Southam',
    byUrl: 'https://en.wikipedia.org/wiki/Ann_Southam',
    imgUrl: 'https://albertaonrecord.ca/uploads/r/paul-d-fleck-library-and-archives-at-banff-centre/c/c/6/cc6f39966a2c66e770825b33cfb4f0fb9c58189d2952c2541636426bddc7d9cd/AS10_2_001_002_142.jpg',
    contributedBy: 'Robert Rowat (https://www.cbcmusic.ca/posts/11372/10-pieces-of-classical-music-everyone-should-know)',
  },
  {
    videoId: '4wvpdBnfiZo',
    name: 'The Imperial March',
    date: 1980,
    url: 'https://en.wikipedia.org/wiki/The_Imperial_March',
    by: 'John Williams',
    byUrl: 'https://en.wikipedia.org/wiki/John_Williams',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/en/7/76/Darth_Vader.jpg',
    for: 'Star Wars: Episode V - The Empire Strikes Back',
    performedBy: 'Vienna Philharmonic Orchestra',
    contributedBy: 'Brian Russell',
  },
  // {
  //   videoId: 'q4ujJImwR3w',
  //   name: 'Piano Sonata No. 1',
  //   date: 1990,
  //   number: 1,
  //   url: 'https://en.wikipedia.org/wiki/Piano_Sonata_No._1_(Vine)',
  //   by: 'Carl Vine',
  //   byUrl: 'https://en.wikipedia.org/wiki/Carl_Vine',
  //   time: 267,
  //   performedBy: 'Dmitri Levkovich',
  //   contributedBy: 'Logan Sobczak',
  // },
];

export default playlist;
