const playlist = [
  {
    videoId: 'mGQLXRTl3Z0',
    date: '1717–1723 (Late Baroque Period)',
    name: 'Suite No. 1 in G major for unaccompanied cello, BWV 1007',
    url: 'https://en.wikipedia.org/wiki/Cello_Suites_(Bach)#Suite_No._1_in_G_major,_BWV_1007',
    by: 'Johann Sebastian Bach',
    byUrl: 'https://en.wikipedia.org/wiki/Johann_Sebastian_Bach',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/93/Young_Bach2.jpg',
  },
  {
    videoId: 'b4IXXpTHjok',
    date: '1764–1771 (Early Classical Period)',
    name: 'Symphony No. 1',
    url: 'https://en.wikipedia.org/wiki/Symphony_No._1_(Mozart)',
    by: 'Wolfgang Amadeus Mozart',
    byUrl: 'https://en.wikipedia.org/wiki/Wolfgang_Amadeus_Mozart',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Wolfgang-amadeus-mozart_2.jpg/500px-Wolfgang-amadeus-mozart_2.jpg',
  },
  {
    videoId: '6z4KK7RWjmk',
    date: '1804–1808 (Classical Period)',
    name: 'Symphony No. 5 in C Minor, Op. 67',
    url: 'https://en.wikipedia.org/wiki/Symphony_No._5_(Beethoven)',
    by: 'Ludwig Von Beethoven',
    byUrl: 'https://en.wikipedia.org/wiki/Ludwig_van_Beethoven',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Beethoven_3.jpg/500px-Beethoven_3.jpg',
  },
  {
    videoId: 'PvdZ1xIgv08',
    date: '1823 (Early Romantic Period)',
    name: 'Du bist die Ruh, D. 776; Op 59, No. 3',
    url: 'https://en.wikipedia.org/wiki/Du_bist_die_Ruh%27',
    by: 'Franz Schubert',
    byUrl: 'https://en.wikipedia.org/wiki/Franz_Schubert',
  },
  {
    videoId: 'kzLGcNwDJW8',
    date: '1830-1832 (Early Romantic Period)',
    name: 'Nocturne in B-flat minor, Op. 9, No. 1',
    url: 'https://en.wikipedia.org/wiki/Nocturnes,_Op._9_(Chopin)',
    by: 'Frédéric Chopin',
    byUrl: 'https://en.wikipedia.org/wiki/Fr%C3%A9d%C3%A9ric_Chopin',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Frederic_Chopin_photo.jpeg/440px-Frederic_Chopin_photo.jpeg',
  },
  {
    videoId: 'FpK1tjbeeA0',
    date: '1856-1861 (Romantic Period)',
    name: 'Piano Quartet No. 1, Op. 25',
    url: 'https://en.wikipedia.org/wiki/Piano_Quartet_No._1_(Brahms)',
    by: 'Johannes Brahms',
    byUrl: 'https://en.wikipedia.org/wiki/Johannes_Brahms',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/11/Johannes_Brahms_1853.jpg',
  },
  {
    videoId: 'KJ_HHRJf0xg',
    date: '1875 (Romantic Period)',
    name: 'Carmen - Habanera',
    url: 'https://en.wikipedia.org/wiki/Habanera_(aria)',
    by: 'Georges Bizet',
    byUrl: 'https://en.wikipedia.org/wiki/Georges_Bizet',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Georges_bizet.jpg/440px-Georges_bizet.jpg',
  },
  {
    videoId: 'IFPwm0e_K98',
    date: '1896 (Late Romantic Period)',
    name: 'Also Sprach Zarathustra, Op. 30',
    url: 'https://en.wikipedia.org/wiki/Also_sprach_Zarathustra_(Strauss)',
    by: 'Richard Strauss',
    byUrl: 'https://en.wikipedia.org/wiki/Richard_Strauss',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Strauss1894.jpg',
  },
  {
    videoId: 'rEGOihjqO9w',
    date: '1900-1901 (Late Romantic Period)',
    name: 'Piano Concerto No. 2 in C minor, Op. 18',
    url: 'https://en.wikipedia.org/wiki/Piano_Concerto_No._2_(Rachmaninoff)',
    by: 'Sergei Rachmaninoff',
    byUrl: 'https://en.wikipedia.org/wiki/Sergei_Rachmaninoff',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Rachmaninoff_1900.jpg/440px-Rachmaninoff_1900.jpg',
  },
  {
    videoId: 'CJYVH_kZkOk',
    date: '1944 (Modern Period)',
    name: 'Appalachian Spring',
    url: 'https://en.wikipedia.org/wiki/Appalachian_Spring',
    by: 'Aaron Copland',
    byUrl: 'https://en.wikipedia.org/wiki/Aaron_Copland',
    imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Aaron_Copland_1962.JPG/440px-Aaron_Copland_1962.JPG',
  },
  {
    videoId: '1seFM7hwYKo',
    date: '1970-1979 (Modern Period)',
    name: 'Glass Houses No. 5',
    by: 'Ann Southam',
    byUrl: 'https://en.wikipedia.org/wiki/Ann_Southam',
    imgUrl: 'https://albertaonrecord.ca/uploads/r/paul-d-fleck-library-and-archives-at-banff-centre/c/c/6/cc6f39966a2c66e770825b33cfb4f0fb9c58189d2952c2541636426bddc7d9cd/AS10_2_001_002_142.jpg',
  },
];

export default playlist;
